infinispan:
  clusterName: infinispan
endpoints:
  hotrod:
    enabled: true
    qop: auth
    serverName: infinispan
  memcached:
    enabled: false
  rest:
    enabled: true
jgroups:
  transport: tcp
  dnsPing:
    address: ""
    recordType: A
keystore:
  alias: server
xsite:
  masterCandidate: true